### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [Cort98/quotalicious#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Cort98** [comment]
Thanks Billy, I guess I was overlooking the meta tags in the bootstrap documentation on my way to the modals. I also added the charset meta.
